#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task

apt-get -y update
apt-get -y install nginx
service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
