#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
service nginx start
