#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
# shellcheck disable=SC2154

hostname=$(hostname)
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/http {/a \        add_header X-Served-By \"$hostname\";" /etc/nginx/nginx.conf
sudo service nginx restart
