#!/usr/bin/env bash
# stop To infinity and beyond indefinitely.

FILE=/var/run/myscript.pid
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && rm $FILE; exit' SIGTERM
trap 'rm $FILE; exit' SIGQUIT
echo "$$" > $FILE
while true
do
    echo "To infinity and beyond"
    sleep 2
done
