#!/usr/bin/env bash
# stop To infinity and beyond indefinitely.
# shellcheck disable=SC2009

File="/var/run/my_process.pid"
if [ "$1" == "start" ];
then
    ./manage_my_process & echo "$!" > $File
    echo "manage_my_process started"
elif [ "$1" == "stop" ];
then
    kill "$(cat $File)"
    rm -f $File
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ];
then
    kill "$(cat $File)"
    rm -f $File
    ./manage_my_process &
    echo "$!" > $File
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
