#!/usr/bin/env bash
# This script is displaying "Best School" 10 time

COUNT=0
while [ $COUNT -lt 10 ]
do
	if [ $COUNT -eq 3 ]
	then
		echo "bad luck"
	elif [ $COUNT -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((COUNT++))
done
