#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

HOUR=0

while [ $HOUR -le 12 ]
do
    echo "Hour: $HOUR"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        (( minutes++ ))
    done
    (( HOUR++ ))
done
