#!/usr/bin/env bash
# gives you information about the school file.

NAME=school
if [ -e $NAME ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $NAME ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $NAME ]; then
    echo "school is a regular file"
fi
