#!/usr/bin/env bash
#  Run Nginx as Nginx  

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
