#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

# Find the PIDs of Gunicorn processes and send the HUP signal to each.
pgrep gunicorn | xargs kill -HUP

echo "Gunicorn processes have been gracefully reloaded."
